<!-- Trae todo el código del header a la página principal -->
<?php include("includes/header.php") ?>

<!-- Aquí va todo el código propio de la página -->
<h1>AQUÍ VAN LAS LIBRERÍAS</h1>
<h2>NO DISPONIBLE POR AHORA</h2>
<p>LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROSLIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROSLIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROSLIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROS LIBROSLIBROS LIBROS LIBROS LIBROS LIBROS</p>

<!-- Trae todo el código del footer a la página principal -->
<?php include("includes/footer.php") ?>
